//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortEZEdit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::Interceptor.Keys FnKey_Edit {
            get {
                return ((global::Interceptor.Keys)(this["FnKey_Edit"]));
            }
            set {
                this["FnKey_Edit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public global::Interceptor.Keys Key_DnREdit {
            get {
                return ((global::Interceptor.Keys)(this["Key_DnREdit"]));
            }
            set {
                this["Key_DnREdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Delay_DnRClickStart {
            get {
                return ((int)(this["Delay_DnRClickStart"]));
            }
            set {
                this["Delay_DnRClickStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Delay_DnrClickRelease {
            get {
                return ((int)(this["Delay_DnrClickRelease"]));
            }
            set {
                this["Delay_DnrClickRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public global::Interceptor.Keys Key_Reset {
            get {
                return ((global::Interceptor.Keys)(this["Key_Reset"]));
            }
            set {
                this["Key_Reset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Delay_ResetPreClick {
            get {
                return ((int)(this["Delay_ResetPreClick"]));
            }
            set {
                this["Delay_ResetPreClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Delay_ResetPostClick {
            get {
                return ((int)(this["Delay_ResetPostClick"]));
            }
            set {
                this["Delay_ResetPostClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F10")]
        public global::Interceptor.Keys Key_Pause {
            get {
                return ((global::Interceptor.Keys)(this["Key_Pause"]));
            }
            set {
                this["Key_Pause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int id_Mouse {
            get {
                return ((int)(this["id_Mouse"]));
            }
            set {
                this["id_Mouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public global::Interceptor.Keys Key_EditRampPlaceModifier {
            get {
                return ((global::Interceptor.Keys)(this["Key_EditRampPlaceModifier"]));
            }
            set {
                this["Key_EditRampPlaceModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public global::Interceptor.Keys FnKey_Ramp {
            get {
                return ((global::Interceptor.Keys)(this["FnKey_Ramp"]));
            }
            set {
                this["FnKey_Ramp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int Delay_ReleaseEditRampPlaceDelay {
            get {
                return ((int)(this["Delay_ReleaseEditRampPlaceDelay"]));
            }
            set {
                this["Delay_ReleaseEditRampPlaceDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Two")]
        public global::Interceptor.Keys FnKey_Shotgun {
            get {
                return ((global::Interceptor.Keys)(this["FnKey_Shotgun"]));
            }
            set {
                this["FnKey_Shotgun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Check_EditToConfirm {
            get {
                return ((bool)(this["Check_EditToConfirm"]));
            }
            set {
                this["Check_EditToConfirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public global::Interceptor.Keys FnKey_Wall {
            get {
                return ((global::Interceptor.Keys)(this["FnKey_Wall"]));
            }
            set {
                this["FnKey_Wall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::Interceptor.Keys FnKey_Floor {
            get {
                return ((global::Interceptor.Keys)(this["FnKey_Floor"]));
            }
            set {
                this["FnKey_Floor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftShift")]
        public global::Interceptor.Keys FnKey_Cone {
            get {
                return ((global::Interceptor.Keys)(this["FnKey_Cone"]));
            }
            set {
                this["FnKey_Cone"] = value;
            }
        }
    }
}
